name: Semantic Versioning and Build

on:
  push:
    branches:
      - main
      - feat/auto-release
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        working-directory: ./jvm-spring-web

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        working-directory: ./jvm-spring-web

    - name: Determine Next Version
      id: determine_version
      run: |
        # Extracting version type (major/minor/patch) from commit message or PR title
        if [[ "$GITHUB_REF" == refs/heads/release/* ]]; then
          VERSION_TYPE="minor"
        elif [[ "$GITHUB_REF" == refs/heads/main ]]; then
          VERSION_TYPE="patch"
        fi
        # Bumping version accordingly using a custom script or Gradle task
        NEW_VERSION=$(./gradlew -q printVersion)
        ./gradlew bumpVersion -Ptype=$VERSION_TYPE
        echo "::set-output name=new_version::$NEW_VERSION"
      working-directory: ./jvm-spring-web

    - name: Commit Version Change
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -am "Bump version to ${{ steps.determine_version.outputs.new_version }}"
        git push origin main
      working-directory: ./jvm-spring-web
